train_test_split_ratios:
  train: 0.75
  test: 0.25
n_cpus: 10
niceness: 3
n_folds: 10
random_state: 94705

common_n_estimators: &common_n_estimators
  - 50
  - 100

common_depths: &common_depths
  - 2
  - 4
  - 8

target_col: &target_col "outcome"
weight_col: &weight_col "hh_wgt"
id_col: &id_col "case_id"
urban_or_rural: "both"
evaluate_on_urban_only: True
use_expanded_data: False


extras:
  - *target_col
  - *weight_col
  - *id_col
  - hhid
  - pid

models_to_run:
  - Stepwise
  - RandomForest
  - Lasso
  - GradientBoosting


  

grid_search_params:
  rf:
    n_estimators: *common_n_estimators
    max_depth: *common_depths
  gb:
    n_estimators: *common_n_estimators
    max_depth: *common_depths
    min_samples_leaf:
      - 1
      - 5
      - 10
    learning_rate:
      - 0.01
      - 0.1
      - 0.5
